spring.application.name=Task-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/Task_manager_db
spring.datasource.username=postgres
spring.datasource.password=Kira20012015

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true